import { GeocodedLocation } from '@/types/location';
import { getCategoryColor } from './categoryColors';

export function generateKML(locations: GeocodedLocation[], filename: string = 'locations'): string {
  const validLocations = locations.filter(
    loc => loc.geocodeStatus === 'success' && loc.latitude && loc.longitude
  );

  // Group locations by category for styling
  const categories = [...new Set(validLocations.map(loc => loc.category))];
  
  // Generate styles for each category
  const styles = categories.map(category => {
    const color = getCategoryColor(category);
    // KML uses AABBGGRR format (Alpha, Blue, Green, Red)
    const kmlColor = hexToKmlColor(color);
    return `  <Style id="style-${sanitizeId(category)}">
    <IconStyle>
      <color>${kmlColor}</color>
      <scale>1.0</scale>
      <Icon>
        <href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
      </Icon>
    </IconStyle>
    <LabelStyle>
      <color>${kmlColor}</color>
    </LabelStyle>
  </Style>`;
  }).join('\n');

  // Generate placemarks
  const placemarks = validLocations.map(loc => {
    const description = [
      `<strong>Category:</strong> ${escapeXml(loc.category)}`,
      loc.neighborhood && `<strong>Area:</strong> ${escapeXml(loc.neighborhood)}`,
      loc.notes && `<p>${escapeXml(loc.notes)}</p>`,
    ].filter(Boolean).join('<br/>');

    return `  <Placemark>
    <name>${escapeXml(loc.name)}</name>
    <description><![CDATA[${description}]]></description>
    <styleUrl>#style-${sanitizeId(loc.category)}</styleUrl>
    <Point>
      <coordinates>${loc.longitude},${loc.latitude},0</coordinates>
    </Point>
  </Placemark>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(filename)}</name>
    <description>Generated by Bulk Location Importer</description>
${styles}
${placemarks}
  </Document>
</kml>`;
}

export function downloadKML(locations: GeocodedLocation[], filename: string = 'locations'): void {
  const kmlContent = generateKML(locations, filename);
  const blob = new Blob([kmlContent], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.kml`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function hexToKmlColor(hex: string): string {
  // Remove # if present
  hex = hex.replace('#', '');
  
  // Parse RGB values
  const r = hex.substring(0, 2);
  const g = hex.substring(2, 4);
  const b = hex.substring(4, 6);
  
  // KML format is AABBGGRR (with full opacity)
  return `ff${b}${g}${r}`;
}

function sanitizeId(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]/g, '-');
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

