import { GeocodedLocation } from '@/types/location';

export function generateGPX(locations: GeocodedLocation[], filename: string = 'locations'): string {
  const validLocations = locations.filter(
    loc => loc.geocodeStatus === 'success' && loc.latitude && loc.longitude
  );

  const waypoints = validLocations.map(loc => {
    const description = [
      loc.category && `Category: ${loc.category}`,
      loc.notes && loc.notes,
    ].filter(Boolean).join('\n');

    return `  <wpt lat="${loc.latitude}" lon="${loc.longitude}">
    <name>${escapeXml(loc.name)}</name>
    <desc>${escapeXml(description)}</desc>
    <type>${escapeXml(loc.category)}</type>
  </wpt>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Bulk Location Importer"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${escapeXml(filename)}</name>
    <desc>Generated by Bulk Location Importer</desc>
    <time>${new Date().toISOString()}</time>
  </metadata>
${waypoints}
</gpx>`;
}

export function downloadGPX(locations: GeocodedLocation[], filename: string = 'locations'): void {
  const gpxContent = generateGPX(locations, filename);
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.gpx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

